version: '3'

services:
  rest-app:
    build: .
    ports:
      - "6000:6000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
